theme: jekyll-theme-modernist
title: Dilimiz
description: Düzgün language tools
fontname: Amiri-Regular
fontttf: /assets/Amiri-Regular.ttf
fonteot: /assets/Amiri-Regular.eot
fontwoff: /assets/Amiri-Regular.woff
fontwoff2: /assets/Amiri-Regular.woff2
google_analytics: G-HF5NYF5MWQ
