theme: jekyll-theme-modernist
title: Dilimiz
description: Düzgün language corrector
fontname: Amiri-Regular
fontsize: 24
fontttf: /assets/Amiri-Regular.ttf
fonteot: /assets/Amiri-Regular.eot
fontwoff: /assets/Amiri-Regular.woff
fontwoff2: /assets/Amiri-Regular.woff2
